grafana:
  enabled: true
  service:
    type: ClusterIP

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    service:
      type: ClusterIP
    persistentVolume:
      enabled: false
  extraScrapeConfigs: |
    - job_name: long-task-api-server
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['api-server-metrics.keda:9001']
          labels:
            application: 'api-server'
  serverFiles:
    alerting_rules.yml:
      groups:
        - name: worker_max_replicas_reached
          rules:
          - alert: worker_max_replicas_reached
            expr: count(kube_pod_info{created_by_kind="ReplicaSet", namespace="keda"}) == 8
            for: 30s
            labels:
              severity: page
            annotations:
              summary: Max replicas of worker pod have been reached. It will not scale any higher.

loki:
  enabled: true
  image:
    tag: 2.9.3
  persistence:
    enabled: false
