grafana:
  enabled: true
  service:
    type: ClusterIP

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    service:
      type: ClusterIP
    persistentVolume:
      enabled: false
  extraScrapeConfigs: |
    - job_name: long-task-api-server
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['api-server-metrics.keda:9001']
          labels:
            application: 'api-server'

loki:
  enabled: true
  persistence:
    enabled: false
