apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
      component: api-server
  template:
    metadata:
      labels:
        app: api-server
        component: api-server
    spec:
      containers:
      - name: server
        image: abhilakshsinghreen/long-task-api-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        - containerPort: 9001
        envFrom:
        - configMapRef:
            name: keda-redis-config
        - configMapRef:
            name: api-server-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  selector:
    app: api-server
    component: api-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-metrics-service
spec:
  selector:
    app: api-server
    component: api-server
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
