apiVersion: v1
kind: Service
metadata:
  name: camb-ai-api-server-loadbalancer-service
spec:
  selector:
    app: camb-ai-api-server
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer